/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Page2RouteImport } from './routes/page2'
import { Route as Page1RouteImport } from './routes/page1'
import { Route as IndexRouteImport } from './routes/index'

const Page2Route = Page2RouteImport.update({
  id: '/page2',
  path: '/page2',
  getParentRoute: () => rootRouteImport,
} as any)
const Page1Route = Page1RouteImport.update({
  id: '/page1',
  path: '/page1',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/page1': typeof Page1Route
  '/page2': typeof Page2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/page1': typeof Page1Route
  '/page2': typeof Page2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/page1': typeof Page1Route
  '/page2': typeof Page2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/page1' | '/page2'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/page1' | '/page2'
  id: '__root__' | '/' | '/page1' | '/page2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Page1Route: typeof Page1Route
  Page2Route: typeof Page2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/page2': {
      id: '/page2'
      path: '/page2'
      fullPath: '/page2'
      preLoaderRoute: typeof Page2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page1': {
      id: '/page1'
      path: '/page1'
      fullPath: '/page1'
      preLoaderRoute: typeof Page1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Page1Route: Page1Route,
  Page2Route: Page2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
